main: io.github.gokborg.playernote.plugin.NotePlugin
name: PlayerNote
version: 1
author: Gokborg, Cj, Link
commands:
  playernote:
    description: Create notes worth remmebering for a player
    aliases: [note]
    permission: playernote.read;playernote.write;playernote.remove
    usage: /note <write, read, remove> [...]