main: io.github.gokborg.playernote.plugin.NotePlugin
name: PlayerNote
version: 1
author: Gokborg, Cj, Link
commands:
  playernote:
    description: Creates a new playernote
    aliases: [pnote, note]
    usage: /pnote <player> <+, -, !> <msg>
    permission: playernote.create
  getplayernote:
    description: Get notes of a player
    aliases: [getnote, getpnote]
    usage: /getpnote <player> [+, -, !] [page number]
    permission: playernote.get
  rmplayernote:
    description: Remove a player note
    aliases: [rmnote, rmpnote]
    usage: /rmnote <player> <number>
    permission: playernote.rm
