main: playernote.plugin.NotePlugin
name: PlayerNote
version: 0.01
author: Cj, Link, Gokborg
commands:
  playernote:
    description: Creates a new playernote
    usage: /playernote [player] [+, -, !] [msg]
    permission: playernote.permission
  getplayernote:
    description: Get notes of a player
    usage: /getplayernote [player] [+ or - or ! or blank]
    permission: getplayernote.permission