main: playernote.plugin.NotePlugin
name: PlayerNote
version: 0.01
author: Gokborg, Cj, Link
commands:
  playernote:
    description: Creates a new playernote
    aliases: [pnote, note]
    usage: /note [player] [+, -, !] [msg]
    permission: playernote.permission
  getplayernote:
    description: Get notes of a player
    aliases: [getnote, getpnote]
    usage: /getnote[player] [+ or - or ! or blank] [page number]
    permission: getplayernote.permission
  rmplayernote:
    description: Get notes of a player
    aliases: [rmnote, rmpnote]
    usage: /rmnote [player] [number]
    permission: rmplayernote.permission
  clearplayernotes:
    description: Get notes of a player
    aliases: [clearpnote, clearnote]
    usage: /clearpnote [player] 
    permission: clearplayernote.permission
  clearservernotes:
    description: Clears the servers notes
    aliases: [wipenotes, svrwipenotes]
    usage: /wipenotes ["confirm"]
    permission: clearservernotes.permission