main: playernote.main
name: PlayerNote
version: 0.01
author: Cj, Link, Gokborg
commands:
  playernote:
    description: Creates a new playernote
    usage: /playernote
    permission: playernote.permission
    